---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 87-master-etcd-snapshot-sh
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /usr/local/bin/etcd-snapshot.sh
        contents:
          source: >-
            data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKClNOQVBTSE9UX0hPU1Q9JHsxfQpTTkFQU0hPVF9ESVI9JHsyOi0vaG9tZS9jb3JlL2V0Y2Qtc25hcHNob3RzfQpTTkFQU0hPVF9EQVlTPSR7MzotMH0KVEhJU19IT1NUPSQoaG9zdG5hbWUpClZBTElEX0RJUlM9Ii9ob21lL2NvcmUgL3Zhci9ob21lL2NvcmUgL3RtcCIKCmVjaG8gIi0tLSBSdW50aW1lIC0tLSIKZWNobyAiU05BUFNIT1RfSE9TVD0ke1NOQVBTSE9UX0hPU1R9IgplY2hvICJTTkFQU0hPVF9ESVI9JHtTTkFQU0hPVF9ESVJ9IgplY2hvICJTTkFQU0hPVF9EQVlTPSR7U05BUFNIT1RfREFZU30iCmVjaG8gIi0tLS0tLS0tLS0tLS0tLSIKCnNob3B0IC1zIG5vY2FzZW1hdGNoCmlmIFtbICJwb2QtbW9kZSIgIT0gIiR7U05BUFNIT1RfSE9TVH0iIF1dICYmIFtbICIke1RISVNfSE9TVH0iICE9ICR7U05BUFNIT1RfSE9TVH0qIF1dOyB0aGVuCiAgICBlY2hvICJUaGlzIG5vZGUgKCR7VEhJU19IT1NUfSkgaXMgbm90IHRoZSBldGNkLXNuYXBzaG90IHRhcmdldCBub2RlICgke1NOQVBTSE9UX0hPU1R9KS4iIAogICAgZXhpdCAwCmZpCgp2YWxpZD0wCmZvciBoIGluICR7VkFMSURfRElSU307IGRvCiAgICBpZiAgW1sgIiR7U05BUFNIT1RfRElSfSIgPX4gXiR7aH0vW2EtekEtejAtOV9dKy4qIF1dOyB0aGVuCiAgICAgICAgdmFsaWQ9MQogICAgICAgIGJyZWFrCiAgICBmaQpkb25lCmlmIFtbICIke3ZhbGlkfSIgPT0gIjAiICBdXTsgdGhlbgogICAgZWNobyAiJHtTTkFQU0hPVF9ESVJ9IGlzIG5vdCBhIHZhbGlkIHRhcmdldCBkaXJlY3RvcnkuIgogICAgZXhpdCAxCmZpCgpta2RpciAtcCAke1NOQVBTSE9UX0RJUn0KCi91c3IvbG9jYWwvYmluL2NsdXN0ZXItYmFja3VwLnNoICR7U05BUFNIT1RfRElSfQoKY2hvd24gLVIgY29yZTpjb3JlICR7U05BUFNIT1RfRElSfQoKc2xlZXAgMQoKaWYgW1sgIiR7U05BUFNIT1RfREFZU30iID09ICIwIiBdXTsgdGhlbgogICAgZWNobyAiU2tpcHBpbmcgc25hcHNob3QgcHVyZ2UuIgogICAgZXhpdCAwCmZpCgplY2hvICItLS0gUHJlLXB1cmdlIHN0YXRlIC0tLSIKbHMgLWwgJHtTTkFQU0hPVF9ESVJ9CgplY2hvICItLS0gUHVyZ2luZyBzdGFsZSBzbmFwc2hvdHMgLS0tIgpmaW5kICR7U05BUFNIT1RfRElSfSAtdHlwZSBmIC1tdGltZSArJHtTTkFQU0hPVF9EQVlTfSAtcHJpbnQgLWRlbGV0ZQo=
        mode: 493
        overwrite: true
...