---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 87-master-etcd-snapshot-sh
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /usr/local/bin/etcd-snapshot.sh
        contents:
          source: >-
            data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKClNOQVBTSE9UX0hPU1Q9JHsxfQpTTkFQU0hPVF9ESVI9JHsyOi0vaG9tZS9jb3JlL2V0Y2Qtc25hcHNob3RzfQpTTkFQU0hPVF9EQVlTPSR7MzotMH0KVEhJU19IT1NUPSQoaG9zdG5hbWUpClZBTElEX0RJUlM9Ii9ob21lL2NvcmUgL3Zhci9ob21lL2NvcmUgL3RtcCIKCmVjaG8gIi0tLSBSdW50aW1lIC0tLSIKZWNobyAiU05BUFNIT1RfSE9TVD0ke1NOQVBTSE9UX0hPU1R9IgplY2hvICJTTkFQU0hPVF9ESVI9JHtTTkFQU0hPVF9ESVJ9IgplY2hvICJTTkFQU0hPVF9EQVlTPSR7U05BUFNIT1RfREFZU30iCmVjaG8gIi0tLS0tLS0tLS0tLS0tLSIKCnNldCAteAoKc2hvcHQgLXMgbm9jYXNlbWF0Y2gKaWYgW1sgInBvZC1tb2RlIiAhPSAiJHtTTkFQU0hPVF9IT1NUfSIgXV0gJiYgW1sgIiR7VEhJU19IT1NUfSIgIT0gJHtTTkFQU0hPVF9IT1NUfSogXV07IHRoZW4KICAgIGVjaG8gIlRoaXMgbm9kZSAoJHtUSElTX0hPU1R9KSBpcyBub3QgdGhlIGV0Y2Qtc25hcHNob3QgdGFyZ2V0IG5vZGUgKCR7U05BUFNIT1RfSE9TVH0pLiIgCiAgICBleGl0IDAKZmkKCnZhbGlkPTAKZm9yIGggaW4gJHtWQUxJRF9ESVJTfTsgZG8KICAgIGlmICBbWyAiJHtTTkFQU0hPVF9ESVJ9IiA9fiBeJHtofS9bYS16QS16MC05X10rLiogXV07IHRoZW4KICAgICAgICB2YWxpZD0xCiAgICAgICAgYnJlYWsKICAgIGZpCmRvbmUKaWYgW1sgIiR7dmFsaWR9IiA9PSAiMCIgIF1dOyB0aGVuCiAgICBlY2hvICIke1NOQVBTSE9UX0RJUn0gaXMgbm90IGEgdmFsaWQgdGFyZ2V0IGRpcmVjdG9yeS4iCiAgICBleGl0IDEKZmkKCm1rZGlyIC1wICR7U05BUFNIT1RfRElSfQoKL3Vzci9sb2NhbC9iaW4vY2x1c3Rlci1iYWNrdXAuc2ggJHtTTkFQU0hPVF9ESVJ9CgpjaG93biAtUiBjb3JlOmNvcmUgJHtTTkFQU0hPVF9ESVJ9CgpzbGVlcCAxCgppZiBbWyAiJHtTTkFQU0hPVF9EQVlTfSIgPT0gIjAiIF1dOyB0aGVuCiAgICBlY2hvICJTa2lwcGluZyBzbmFwc2hvdCBwdXJnZS4iCiAgICBleGl0IDAKZmkKCmVjaG8gIi0tLSBQcmUtcHVyZ2Ugc3RhdGUgLS0tIgpscyAtbCAke1NOQVBTSE9UX0RJUn0KCmVjaG8gIi0tLSBQdXJnaW5nIHN0YWxlIHNuYXBzaG90cyAtLS0iCmZpbmQgJHtTTkFQU0hPVF9ESVJ9IC10eXBlIGYgLW10aW1lICR7U05BUFNIT1RfREFZU30gLXByaW50IC1kZWxldGUK
        mode: 493
        overwrite: true
...