---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-snapshot-sync-sh
data:
  etcd-snapshot-sync.sh: |+
    #! /usr/bin/env bash
    
    set -x

    {{- if eq .Values.mode "pv" }}
      rsync --archive --delete --verbose --human-readable \
        --rsh 'ssh -l core -o "StrictHostKeyChecking=no"' \
        ${2}/ ${3}/
    {{- else }}
      {{ range $i, $n := (lookup "v1" "Node" "" "").items }}
        {{ $l := get $n.metadata.labels "etcd-snapshot.taranto.dev/role" }}
        {{- if eq $l "mirror" }}
          rsync --archive --delete --verbose --human-readable \
            --rsh 'ssh -l core -o "StrictHostKeyChecking=no"' \
            ${2}/ {{ print $n.metadata.name }}:${3}/
        {{- end }}
      {{- end }}
    {{- end }}
