# https://access.redhat.com/articles/4047481
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-snapshotter
  labels:
    {{ .Values.labelDomain }}/app: {{ .Release.Name }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            etcd-snapshot.{{ .Values.labelDomain }}/role: snapshot
          tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          restartPolicy: Never
          {{- if eq .Values.serviceAccount.use true }}
          serviceAccountName: etcd-snapshot
          {{- end }}
          terminationGracePeriodSeconds: 1
          volumes:
          - name: source-dir
            hostPath:
              path: {{ .Values.snapshot.directory }}
          - name: target-dir
            persistentVolumeClaim: 
              claimName: {{ .Values.storage.pvName }}
          - name: host
            hostPath:
              path: /
          initContainers:
          - name: etcd-snapshotter
            image: {{ .Values.image }} 
            imagePullPolicy: IfNotPresent
            command:
            - "chroot"
            - "/host"
            - "/usr/local/bin/etcd-snapshot.sh"
            - "pod-mode"
            - "{{ .Values.snapshot.directory }}"
            - "{{ .Values.snapshot.purgeDays }}"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
            volumeMounts:
            - name: host
              mountPath: /host
          containers:
          - name: etcd-snapshot-sync
            image: {{ .Values.image }} 
            imagePullPolicy: IfNotPresent
            command:
            # - "sleep"
            # - "1800"
            - "/etcd-snapshot-sync.sh"
            - "/source-dir"
            - "/target-dir"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
            volumeMounts:
            - name: source-dir
              mountPath: /source-dir
              readOnly: false          
            - name: target-dir
              mountPath: /target-dir
              readOnly: false          
...
