# https://access.redhat.com/articles/4047481
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-snapshotter
  labels:
    {{ .Values.labelDomain }}/app: {{ .Release.Name }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            etcd-snapshot.{{ .Values.labelDomain }}/role: snapshot
          tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          restartPolicy: Never
          {{- if eq .Values.serviceAccount.use true }}
          serviceAccountName: etcd-snapshot
          {{- end }}
          terminationGracePeriodSeconds: 1
          volumes:
          - name: etcd-snapshot-sync-sh
            configMap:
              name: etcd-snapshot-sync-sh
              defaultMode: 0755
          - name: host
            hostPath:
              path: /
          - name: source-dir
            hostPath:
              path: {{ .Values.snapshot.directory }}
          # - name: ssh-key
          #   secret:
          #     secretName: ssh-key
          #     defaultMode: 0400
          #     items:
          #     - key: ssh-privatekey
          #       path: id_rsa
          {{- if eq .Values.mode "pv" }}
          - name: target-dir
            persistentVolumeClaim: 
              claimName: {{ .Values.pv.name }}
          {{- end }}
          initContainers:
          - name: snapshotter
            image: {{ .Values.image }} 
            imagePullPolicy: IfNotPresent
            command:
            - "chroot"
            - "/host"
            - "/usr/local/bin/etcd-snapshot.sh"
            - "pod-mode"
            - "{{ .Values.snapshot.directory }}"
            - "{{ .Values.snapshot.purgeDays }}"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
            volumeMounts:
            - name: host
              mountPath: /host
          containers:
          - name: syncer
            image: {{ .Values.image }} 
            imagePullPolicy: IfNotPresent
            command:
            # - "sleep"
            # - "600"
            - "/etcd-snapshot-sync/etcd-snapshot-sync.sh"
            - "/source-dir"
            - "/target-dir"
            securityContext:
              privileged: true
              runAsUser: 0
              runAsGroup: 0
            volumeMounts:
            - name: etcd-snapshot-sync-sh
              mountPath: /etcd-snapshot-sync
            - name: source-dir
              mountPath: /source-dir
              readOnly: false          
            # - name: ssh-key
            #   mountPath: /root/.ssh
            {{- if eq .Values.mode "pv" }}
            - name: target-dir
              mountPath: /target-dir
              readOnly: false          
            {{- end }}
...
