{{- if eq .Values.mode "pv" }}

{{- if .Values.pv.storageClassName }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name | quote }}
provisioner: nfs.csi.k8s.io
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: Immediate
{{- end }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name | quote }}
  labels:
  {{- template "snapshot.labels" . }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Release.Name | quote }}

  {{- if eq .Values.pv.driver "csi" }}
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: {{ .Release.Name | quote}}
    volumeAttributes:
      server: {{ .Values.pv.server }}
      share: {{ .Values.pv.path }}
  {{- else if eq .Values.pv.driver "intree" }}
  nfs:
    server: {{ .Values.pv.server }}
    path: {{ .Values.pv.path }}
  {{- end }}
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name | quote }}
  labels:
  {{- template "snapshot.labels" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.capacity }}
    limits:
      storage: {{ .Values.pv.capacity }}
  storageClassName: {{ .Release.Name | quote }}
{{- end }}