debug: false
# Node is in UTC, which is +5 from a real TZ.
schedule: "19 * * * *"

# pv, snyc

# pv = /target-dir is PV-backed
# sync = use snapshot.directory and then sync to 
#    same on nodes with role=mirror label.

debug: false
mode: sync
snapshot:
  directory: "/var/home/core/etcd-snapshots"
  purgeDays: 3

pv:
  name: etcd-snapshot
  driver: csi
  capacity: 100G
  storageClassName: etcd-snapshot
  server: truenas.0.taranto.dev
  path: /mnt/pool-0/backups/ocpa

labelDomain: taranto.dev
namespace: etcd-snapshot
serviceAccount:
  use: true
  name: etcd-snapshot

image: staranto/etcd-snapshot:0.1.5
