cronjob:
  # Node is in UTC, which is -5 from a real TZ.
  schedule: "0 5,17 * * *"

labelDomain: taranto.dev

namespace: etcd-snapshot

serviceAccount:
  use: true
  name: etcd-snapshot

snapshot:
  directory: "/var/home/core/etcd-snapshots"
  purgeDays: 3

storage:
  baseName: etcd-snapshot
  capacity: 100G
  driver: csi
  storageClassName: etcd-snapshot
  server: truenas.0.taranto.dev
  path: /mnt/pool-0/backups/ocpa
