# Node is in UTC, which is +5/+4 from EST/EDT.
schedule: "30 13 * * *"

# pv = /target-dir is PV-backed
# sync = use snapshot.directory and then sync to 
#    same dir on nodes with role=mirror label.
mode: pv

pv:
  name: etcd-snapshot
  driver: intree
  capacity: 100G
  storageClassName: etcd-snapshot
  server: truenas.0.taranto.dev
  path: /mnt/pool-0/backups/ocpb

sync:
  # The secret name pre-deployed to be used by rsync when syncing from the
  # snapshot node to the mirror(s).  The private key is required to be
  # the 'private' key in the secret.
  # TODO: Use the secret available as part of cluster install.
  sshSecret: ssh-key-pair

# Used to build the FQDN for the mirror nodes to sync snapshots to.  It looks
# like there is some inconsistency between 4.x releases as to how RHCOS
# resolves host names.  We're using short names, so this will append the 
# remainder of the FQDN.  
# TODO: To be tested -- AWS.
baseDomain: 0.taranto.dev

debug:
  # Put the nodes to sleep without actually running the snapshot or sync.
  active: false
  # How long they'll sleep for.  Note you can use # of seconds or use a m/h/d
  # qualifier.  infinity is also a poor option.
  timeout: 30m

image: staranto/etcd-snapshot:0.1.5

labelDomain: taranto.dev
# OCP 4.7 uses the hateful dirty checking in its cluster-backup.sh.  Set this 
# value to "4.7" to include the --force option.  This is a workaround because 
# it doesn't look like the privileged pod has access to the host network.  
# So the oc command in cluster-backup.sh fails when trying to hit 
# https://localhost:6443.
# TODO: Figure out how to run a privileged pod w/access to host network.
ocpVersion: "4.6"

serviceAccount:
  # Keep this at true.  Results will be indeterminate until I figure out 
  # exactly how I want to handle pre-existings SA's.
  use: true

snapshot:
  # On-node directory where snapshot will be stored and synced to on mirrors. 
  # TODO: Validate and fail in the chart.
  directory: "/var/home/core/etcd-snapshots"
  # Required number of days where old snapshots will age out and be 
  # automatically purged.  Use 0 to disable. 
  # TODO: Make this optional.  If missing, assume 0.
  purgeDays: 1

tolerationLabelKey: node-role.kubernetes.io/master
